[[rules]]
id = "generic-api-key"
description = "Detected a Generic API Key, potentially exposing access to various services and sensitive operations."
regex = '''(?i)(?:key|api|token|secret|client|passwd|password|auth|access)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([0-9a-z\-_.=]{10,150})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
tags = [
    "key","api","token","secret","client","passwd","password","auth","access",
]

[[rules]]
description = "APP_SECRET"
regex = '''APP_SECRET[=]["'\s]*[a-zA-Z0-9-_]+'''
tags = ["appsecret"]


[[rules]]
  description = "Database URI"
  regex = '''DATABASE_URI\s*=\s*["']?postgresql:\/\/[^\s"']+'''
  secretGroup = 0
  tags = ["database", "uri", "postgresql"]


[[rules]]
description = "Generic API Key"
regex = '''(?i)api[_-]?key["'\s:]*[=]["'\s]*[a-zA-Z0-9-]{16,45}'''
tags = ["apikey"]


[[rules]]
description = "Database User"
regex = '''DB_USER[=]["'\s]*[a-zA-Z0-9-_]+'''
tags = ["dbuser"]

[[rules]]
description = "Database Password"
regex = '''DB_PASSWORD[=]["'\s]*[a-zA-Z0-9-_]+'''
tags = ["dbpassword"]

[[rules]]
description = "Database Host"
regex = '''DB_HOST[=]["'\s]*[a-zA-Z0-9-.]+'''
tags = ["dbhost"]

[[rules]]
description = "Database Port"
regex = '''DB_PORT[=]["'\s]*[0-9]{1,5}'''
tags = ["dbport"]

[[rules]]
description = "API Key"
regex = '''API_KEY[=]["'\s]*[a-zA-Z0-9-_]+'''
tags = ["apikey"]

[[rules]]
description = "Feature Names"
regex = '''FEATURE_NAMES[=]["'\s]*[a-zA-Z0-9-_]+'''
tags = ["featurenames"]

[[rules]]
description = "Hyperparameter C"
regex = '''HYPERPARAM_C[=]["'\s]*[0-9]+'''
tags = ["hyperparamc"]

[[rules]]
description = "Test Size"
regex = '''TEST_SIZE[=]["'\s]*[0-9.]+'''
tags = ["testsize"]

[[rules]]
description = "Random State"
regex = '''RANDOM_STATE[=]["'\s]*[0-9]+'''
tags = ["randomstate"]

